# Generated by Django 3.1.2 on 2020-12-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0004_auto_20201212_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Education',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='SERVICES',
            new_name='services',
        ),
    ]
