# Generated by Django 3.1.2 on 2020-12-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0009_auto_20201212_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='template',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
